export enum CardRankValue {
	Two = 2,
	Three = 3,
	Four = 4,
	Five = 5,
	Six = 6,
	Seven = 7,
	Eight = 8,
	Nine = 9,
	Ten = 10,
	Jack = 10,
	Queen = 10,
	King = 10,
	Ace = 11,
}

export const CARD_VALUE_MAP = {
	'2': CardRankValue.Two,
	'3': CardRankValue.Three,
	'4': CardRankValue.Four,
	'5': CardRankValue.Five,
	'6': CardRankValue.Six,
	'7': CardRankValue.Seven,
	'8': CardRankValue.Eight,
	'9': CardRankValue.Nine,
	'10': CardRankValue.Ten,
	J: CardRankValue.Jack,
	Q: CardRankValue.Queen,
	K: CardRankValue.King,
	A: CardRankValue.Ace,
} as const
