import { StyleSheet } from 'react-native'

export const TYPOGRAPHY = StyleSheet.create({
	H1: {
		fontSize: 23,
		fontFamily: 'Dosis-Bold',
		textTransform: 'uppercase',
		color: '#FFFFFF',
		shadowColor: '#0084FF',
		shadowOffset: { width: 0, height: 2 },
		shadowOpacity: 0.5,
		shadowRadius: 2,
	},
	H2: {
		fontSize: 34,
		fontFamily: 'DoHyeon-Regular',
		textTransform: 'uppercase',
		color: '#FFFFFF',
	},
	H3: {
		fontSize: 28,
		fontFamily: 'Dosis-SemiBold',
		color: '#FFFFFF',
		lineHeight: 32,
	},
	H4: {
		fontSize: 32,
		fontFamily: 'DoHyeon-Regular',
		color: '#FFFFFF',
		textTransform: 'uppercase',
	},
	H5: {
		fontSize: 20,
		fontFamily: 'Dosis-SemiBold',
		color: '#FFFFFF',
		textTransform: 'uppercase',
		lineHeight: 21,
	},
	H6: {
		fontSize: 20,
		fontFamily: 'Dosis-Regular',
		color: '#FFFFFF',
		textTransform: 'uppercase',
		lineHeight: 23,
	},
	H7: {
		fontSize: 22,
		fontFamily: 'Dosis-ExtraBold',
		color: '#FFFFFF',
		textTransform: 'capitalize',
		lineHeight: 22,
	},
	H8: {
		fontSize: 20,
		fontFamily: 'Dosis-Medium',
		color: '#FFFFFF',
		lineHeight: 24,
	},
	H9: {
		fontSize: 20,
		fontFamily: 'Dosis-ExtraBold',
		color: '#FFFFFF',
		lineHeight: 22,
		textTransform: 'capitalize',
		textDecorationLine: 'underline',
	},
	H10: {
		fontSize: 28,
		fontFamily: 'DoHyeon-Regular',
		color: '#FFFFFF',
	},
	H11: {
		fontSize: 22,
		fontFamily: 'Dosis-ExtraBold',
		textTransform: 'uppercase',
	},
	H12: {
		fontSize: 24,
		fontFamily: 'Dosis-Bold',
		color: '#FFFFFF',
		textTransform: 'uppercase',
	},
	H13: {
		fontSize: 24,
		fontFamily: 'DoHyeon-Regular',
	},
	H14: {
		fontSize: 30,
		fontFamily: 'DoHyeon-Regular',
		color: '#FFFFFF',
		textTransform: 'uppercase',
	},
	H15: {
		fontSize: 26,
		fontFamily: 'DoHyeon-Regular',
		color: '#76BDFF',
		textTransform: 'uppercase',
	},
	H16: {
		fontSize: 22,
		fontFamily: 'Dosis-SemiBold',
		color: '#FFFFFF',
		textTransform: 'uppercase',
	},
	H17: {
		fontSize: 18,
		fontFamily: 'DoHyeon-Regular',
		textTransform: 'uppercase',
	},
	H18: {
		fontSize: 16,
		fontFamily: 'DoHyeon-Regular',
		color: '#0084FF',
	},
	H19: {
		fontSize: 14,
		fontFamily: 'DoHyeon-Regular',
		color: '#052C66',
		lineHeight: 15,
	},
	H20: {
		fontSize: 24,
		fontFamily: 'DoHyeon-Regular',
		color: '#FFFFFF',
		lineHeight: 22,
		letterSpacing: -2,
		textTransform: 'uppercase',
	},
	H21: {
		fontSize: 102,
		fontFamily: 'Dosis-ExtraBold',
		textTransform: 'uppercase',
	},
	H22: {
		fontSize: 38,
		fontFamily: 'Dosis-ExtraBold',
		textTransform: 'uppercase',
	},
	H23: {
		fontSize: 28,
		fontFamily: 'Dosis-Bold',
		color: '#052C66',
	},
	H24: {
		fontSize: 32,
		fontFamily: 'DoHyeon-Regular',
		color: '#FFFFFF',
	},
	H25: {
		fontSize: 24,
		fontFamily: 'DoHyeon-Regular',
		color: '#FFFFFF',
		textTransform: 'uppercase',
	},
	H26: {
		fontSize: 20,
		fontFamily: 'Dosis-SemiBold',
		color: '#FFFFFF',
		textTransform: 'uppercase',
	},
	H27: {
		fontSize: 28,
		fontFamily: 'DoHyeon-Regular',
		textTransform: 'uppercase',
	},
	H28: {
		fontSize: 18,
		fontFamily: 'Dosis-Medium',
		color: '#FFFFFF',
		textTransform: 'uppercase',
		textDecorationLine: 'underline',
	},
	H29: {
		fontSize: 18,
		fontFamily: 'DoHyeon-Regular',
		color: '#59073B',
		textTransform: 'uppercase',
	},
	H30: {
		fontSize: 22,
		fontFamily: 'DoHyeon-Regular',
		color: '#59073B',
		textTransform: 'uppercase',
	},
	H31: {
		fontSize: 30,
		fontFamily: 'DoHyeon-Regular',
		color: '#FFFFFF',
		textTransform: 'uppercase',
	},
	H32: {
		fontSize: 28,
		fontFamily: 'DoHyeon-Regular',
		color: '#FFFFFF',
		textTransform: 'uppercase',
	},
	H33: {
		fontSize: 26,
		fontFamily: 'DoHyeon-Regular',
		color: '#FFFFFF',
		textTransform: 'uppercase',
	},
	H34: {
		fontSize: 24,
		fontFamily: 'DoHyeon-Regular',
		color: '#FFFFFF',
		textTransform: 'uppercase',
	},
	H35: {
		fontSize: 18,
		fontFamily: 'DoHyeon-Regular',
		color: '#0e0f12',
		textTransform: 'lowercase',
	},
})
